# Generated by Django 3.0.6 on 2020-05-05 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='identifier',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Identifier'),
            preserve_default=False,
        ),
    ]
