# Generated by Django 3.0.6 on 2020-05-07 18:46

import ckeditor.fields
import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cv_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='color',
            field=colorfield.fields.ColorField(default='#3e3e3e', max_length=18),
        ),
        migrations.AddField(
            model_name='cv',
            name='hobby',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Knowledge'),
        ),
    ]
