# Generated by Django 3.0.6 on 2020-05-07 18:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200507_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='hobby',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Hobby'),
        ),
    ]
